"""ORBITRA — Universal semantic vocabulary + multilingual translation index.

Architecture:
- DOMAINS: ~35 semantic domains covering all major industries/topics
- CONCEPTS: ~1200 English terms with domain tags, synonyms, and related terms
- TRANSLATIONS: per-language translation tables keyed by concept_id
- Stemming: simple suffix-stripping Porter-lite for morphological matching
- Domain inference: from matched concepts, infer the primary domain(s)
"""

from __future__ import annotations
from dataclasses import dataclass, field

# ──────────────────────────────────────────────────────────────────────────────
# DOMAIN TAXONOMY
# ──────────────────────────────────────────────────────────────────────────────

DOMAINS = {
    "sports":         "Sports & Fitness",
    "travel":         "Travel & Tourism",
    "food":           "Food & Hospitality",
    "tech":           "Technology & Software",
    "business":       "Business & Commerce",
    "finance":        "Finance & Banking",
    "education":      "Education & Learning",
    "health":         "Healthcare & Medical",
    "legal":          "Legal & Government",
    "realestate":     "Real Estate & Property",
    "retail":         "Retail & E-commerce",
    "manufacturing":  "Manufacturing & Industrial",
    "media":          "Media & Entertainment",
    "fashion":        "Fashion & Apparel",
    "automotive":     "Automotive & Transport",
    "energy":         "Energy & Environment",
    "agriculture":    "Agriculture & Food Production",
    "logistics":      "Logistics & Supply Chain",
    "hr":             "Human Resources & Recruitment",
    "marketing":      "Marketing & Advertising",
    "construction":   "Construction & Engineering",
    "beauty":         "Beauty & Wellness",
    "art":            "Art & Culture",
    "science":        "Science & Research",
    "nonprofit":      "Nonprofit & Social",
    "government":     "Government & Public Sector",
    "events":         "Events & Conferences",
    "pets":           "Pets & Animals",
    "home":           "Home & Garden",
    "gaming":         "Gaming & Esports",
    "crypto":         "Crypto & Blockchain",
    "insurance":      "Insurance & Risk",
    "aerospace":      "Aerospace & Defense",
    "telecom":        "Telecommunications",
    "general":        "General",
}


# ──────────────────────────────────────────────────────────────────────────────
# CONCEPT TABLE
# Each concept: (concept_id, domain, synonyms_list)
# synonyms_list: all English words/phrases that map to this concept
# ──────────────────────────────────────────────────────────────────────────────

CONCEPTS: list[tuple[str, str, list[str]]] = [
    # ── SPORTS ──
    ("basketball",     "sports", ["basketball", "bball", "hoops"]),
    ("football",       "sports", ["football", "soccer", "futbol"]),
    ("golf",           "sports", ["golf", "golfing", "golf course"]),
    ("tennis",         "sports", ["tennis", "tennis court"]),
    ("swimming",       "sports", ["swimming", "swim", "pool", "aquatic"]),
    ("volleyball",     "sports", ["volleyball"]),
    ("badminton",      "sports", ["badminton"]),
    ("baseball",       "sports", ["baseball"]),
    ("rugby",          "sports", ["rugby"]),
    ("cricket",        "sports", ["cricket"]),
    ("cycling",        "sports", ["cycling", "cycling", "bike", "bicycle"]),
    ("martial_arts",   "sports", ["martial arts", "karate", "judo", "taekwondo", "mma", "kung fu"]),
    ("gymnastics",     "sports", ["gymnastics", "gymnastic"]),
    ("athletics",      "sports", ["athletics", "track", "field", "running", "marathon"]),
    ("skiing",         "sports", ["skiing", "ski", "snowboard", "winter sport"]),
    ("ice_hockey",     "sports", ["ice hockey", "hockey"]),
    ("climbing",       "sports", ["climbing", "rock climbing", "bouldering"]),
    ("triathlon",      "sports", ["triathlon", "ironman"]),
    ("esports",        "sports", ["esports", "esport", "competitive gaming"]),
    ("fitness",        "sports", ["fitness", "gym", "workout", "exercise", "training"]),
    ("yoga",           "sports", ["yoga", "pilates", "meditation"]),
    ("sports_camp",    "sports", ["sports camp", "camp", "summer camp", "training camp", "athletic camp"]),
    ("sports_academy", "sports", ["academy", "sports academy", "training center", "sports school"]),
    ("coach",          "sports", ["coach", "coaching", "trainer", "instructor"]),
    ("tournament",     "sports", ["tournament", "championship", "competition", "league", "cup"]),
    ("athlete",        "sports", ["athlete", "player", "junior", "youth"]),
    ("stadium",        "sports", ["stadium", "arena", "court", "pitch", "field"]),
    ("sports_agent",   "sports", ["sports agent", "agent", "reseller", "promoter"]),

    # ── TRAVEL ──
    ("travel_agency",  "travel", ["travel agency", "travel agent", "tour operator", "travel company"]),
    ("tour",           "travel", ["tour", "tourism", "tourist", "sightseeing", "excursion"]),
    ("hotel",          "travel", ["hotel", "resort", "hostel", "accommodation", "lodging"]),
    ("flight",         "travel", ["flight", "airline", "airfare", "aviation"]),
    ("cruise",         "travel", ["cruise", "cruise ship", "sailing"]),
    ("visa",           "travel", ["visa", "immigration", "passport"]),
    ("travel_package", "travel", ["travel package", "holiday package", "all inclusive", "group tour"]),
    ("backpacking",    "travel", ["backpacking", "budget travel", "hostel"]),
    ("luxury_travel",  "travel", ["luxury travel", "premium", "vip", "exclusive"]),
    ("adventure",      "travel", ["adventure", "outdoor", "hiking", "trekking", "expedition"]),
    ("cultural",       "travel", ["cultural", "heritage", "museum", "history", "local"]),
    ("booking",        "travel", ["booking", "reservation", "ticket", "itinerary"]),
    ("guide",          "travel", ["guide", "travel guide", "local guide"]),

    # ── FOOD & HOSPITALITY ──
    ("restaurant",     "food", ["restaurant", "eatery", "dining", "dine", "bistro", "brasserie"]),
    ("cafe",           "food", ["cafe", "coffee", "coffeehouse", "coffee shop", "bakery"]),
    ("catering",       "food", ["catering", "caterer", "event catering"]),
    ("bar",            "food", ["bar", "pub", "nightclub", "lounge"]),
    ("food_delivery",  "food", ["food delivery", "takeaway", "takeout", "delivery"]),
    ("street_food",    "food", ["street food", "food market", "food stall"]),
    ("organic",        "food", ["organic", "vegan", "vegetarian", "plant based", "healthy food"]),
    ("beverage",       "food", ["beverage", "drink", "juice", "tea", "wine", "beer", "spirits"]),
    ("bakery",         "food", ["bakery", "bread", "pastry", "cake"]),
    ("food_supplier",  "food", ["food supplier", "food distributor", "food wholesaler"]),

    # ── TECHNOLOGY ──
    ("software",       "tech", ["software", "app", "application", "platform", "tool", "saas"]),
    ("hardware",       "tech", ["hardware", "device", "computer", "server"]),
    ("ai",             "tech", ["artificial intelligence", "ai", "machine learning", "ml", "deep learning"]),
    ("cybersecurity",  "tech", ["cybersecurity", "security", "firewall", "encryption", "infosec"]),
    ("cloud",          "tech", ["cloud", "cloud computing", "aws", "azure", "saas", "paas"]),
    ("data",           "tech", ["data", "analytics", "big data", "database", "data science"]),
    ("mobile",         "tech", ["mobile", "app", "ios", "android", "smartphone"]),
    ("web",            "tech", ["web", "website", "web development", "frontend", "backend"]),
    ("iot",            "tech", ["iot", "internet of things", "sensor", "smart device"]),
    ("blockchain",     "tech", ["blockchain", "crypto", "nft", "defi", "web3"]),
    ("startup",        "tech", ["startup", "tech startup", "venture", "incubator"]),
    ("api",            "tech", ["api", "integration", "webhook", "sdk"]),

    # ── BUSINESS ──
    ("company",        "business", ["company", "corporation", "business", "enterprise", "firm", "organisation"]),
    ("supplier",       "business", ["supplier", "vendor", "distributor", "wholesaler", "manufacturer"]),
    ("partner",        "business", ["partner", "partnership", "joint venture", "collaboration"]),
    ("consulting",     "business", ["consulting", "consultant", "advisory", "strategy"]),
    ("services",       "business", ["services", "service provider", "managed service", "outsourcing"]),
    ("import_export",  "business", ["import", "export", "trade", "customs", "freight", "international trade"]),
    ("franchise",      "business", ["franchise", "franchisor", "franchisee", "licensing"]),
    ("b2b",            "business", ["b2b", "business to business", "corporate", "enterprise"]),
    ("b2c",            "business", ["b2c", "consumer", "retail", "direct to consumer"]),
    ("startup_biz",    "business", ["startup", "incubator", "accelerator", "pitch"]),
    ("merger",         "business", ["merger", "acquisition", "m&a", "buyout"]),
    ("procurement",    "business", ["procurement", "purchasing", "sourcing", "tender"]),

    # ── FINANCE ──
    ("bank",           "finance", ["bank", "banking", "financial institution", "credit union"]),
    ("investment",     "finance", ["investment", "investor", "fund", "portfolio", "equity"]),
    ("insurance",      "finance", ["insurance", "insurer", "policy", "premium", "claim"]),
    ("accounting",     "finance", ["accounting", "bookkeeping", "audit", "cpa", "tax"]),
    ("loan",           "finance", ["loan", "mortgage", "credit", "lending", "debt"]),
    ("fintech",        "finance", ["fintech", "payment", "paytech", "digital banking"]),
    ("trading",        "finance", ["trading", "forex", "stocks", "commodities", "futures"]),
    ("wealth",         "finance", ["wealth management", "private banking", "asset management"]),

    # ── EDUCATION ──
    ("school",         "education", ["school", "primary school", "secondary school", "high school"]),
    ("university",     "education", ["university", "college", "higher education", "campus"]),
    ("course",         "education", ["course", "class", "lesson", "curriculum", "program"]),
    ("online_edu",     "education", ["online learning", "elearning", "mooc", "distance learning"]),
    ("language_school","education", ["language school", "language course", "esl", "english school"]),
    ("tutoring",       "education", ["tutoring", "tutor", "private lesson", "coaching"]),
    ("vocational",     "education", ["vocational", "trade school", "apprenticeship", "certification"]),
    ("scholarship",    "education", ["scholarship", "grant", "bursary", "financial aid", "fellowship"]),
    ("kindergarten",   "education", ["kindergarten", "preschool", "nursery", "daycare", "childcare"]),
    ("international_school", "education", ["international school", "expat school", "bilingual school"]),

    # ── HEALTH & MEDICAL ──
    ("hospital",       "health", ["hospital", "clinic", "medical center", "healthcare"]),
    ("doctor",         "health", ["doctor", "physician", "specialist", "gp", "surgeon"]),
    ("pharmacy",       "health", ["pharmacy", "drugstore", "pharmaceutical", "chemist"]),
    ("dental",         "health", ["dental", "dentist", "orthodontist", "teeth"]),
    ("mental_health",  "health", ["mental health", "therapy", "counseling", "psychiatry"]),
    ("wellness",       "health", ["wellness", "spa", "massage", "holistic", "alternative medicine"]),
    ("nutrition",      "health", ["nutrition", "dietitian", "supplement", "vitamins"]),
    ("medical_device", "health", ["medical device", "equipment", "diagnostic", "prosthetics"]),
    ("telemedicine",   "health", ["telemedicine", "telehealth", "online doctor", "remote consultation"]),

    # ── LEGAL ──
    ("law_firm",       "legal", ["law firm", "lawyer", "attorney", "solicitor", "barrister", "legal services"]),
    ("contract",       "legal", ["contract", "agreement", "legal document", "clause"]),
    ("intellectual_property", "legal", ["intellectual property", "patent", "trademark", "copyright"]),
    ("compliance",     "legal", ["compliance", "regulatory", "regulation", "governance"]),
    ("litigation",     "legal", ["litigation", "lawsuit", "dispute", "arbitration", "mediation"]),
    ("notary",         "legal", ["notary", "notarial", "deed", "certification"]),

    # ── REAL ESTATE ──
    ("property",       "realestate", ["property", "real estate", "realty", "housing"]),
    ("agent_re",       "realestate", ["estate agent", "real estate agent", "realtor", "property agent"]),
    ("rental",         "realestate", ["rental", "rent", "lease", "landlord", "tenant"]),
    ("commercial_re",  "realestate", ["commercial property", "office space", "retail space", "warehouse"]),
    ("luxury_re",      "realestate", ["luxury property", "villa", "penthouse", "mansion"]),
    ("development",    "realestate", ["property development", "developer", "construction", "new build"]),
    ("mortgage_re",    "realestate", ["mortgage", "home loan", "property loan"]),

    # ── RETAIL & E-COMMERCE ──
    ("ecommerce",      "retail", ["ecommerce", "online store", "online shop", "marketplace"]),
    ("retail_store",   "retail", ["retail store", "shop", "boutique", "outlet"]),
    ("dropshipping",   "retail", ["dropshipping", "fulfillment", "third party logistics"]),
    ("wholesale",      "retail", ["wholesale", "bulk", "trade price", "distributor"]),
    ("marketplace",    "retail", ["marketplace", "platform", "amazon", "alibaba", "shopify"]),
    ("brand",          "retail", ["brand", "branding", "label", "private label"]),

    # ── MANUFACTURING ──
    ("factory",        "manufacturing", ["factory", "manufacturing", "production", "plant"]),
    ("oem",            "manufacturing", ["oem", "odm", "contract manufacturing", "custom manufacturing"]),
    ("quality",        "manufacturing", ["quality control", "qc", "inspection", "certification", "iso"]),
    ("machinery",      "manufacturing", ["machinery", "equipment", "industrial", "automation"]),
    ("raw_material",   "manufacturing", ["raw material", "material", "component", "part"]),
    ("packaging",      "manufacturing", ["packaging", "package", "box", "container"]),

    # ── MEDIA & ENTERTAINMENT ──
    ("music",          "media", ["music", "musician", "band", "recording", "label", "concert"]),
    ("film",           "media", ["film", "movie", "cinema", "video production", "streaming"]),
    ("publishing",     "media", ["publishing", "book", "magazine", "journal", "newspaper"]),
    ("photography",    "media", ["photography", "photographer", "photo", "studio"]),
    ("podcast",        "media", ["podcast", "audio", "radio"]),
    ("social_media",   "media", ["social media", "influencer", "content creator", "youtube"]),
    ("advertising",    "media", ["advertising", "ad agency", "creative agency", "media buying"]),
    ("pr",             "media", ["public relations", "pr", "communications", "press"]),

    # ── FASHION ──
    ("clothing",       "fashion", ["clothing", "fashion", "apparel", "wear", "garment", "textile"]),
    ("luxury_fashion", "fashion", ["luxury", "designer", "couture", "high end"]),
    ("sportswear",     "fashion", ["sportswear", "activewear", "athletic wear", "gym wear"]),
    ("jewelry",        "fashion", ["jewelry", "jewellery", "accessories", "watch"]),
    ("footwear",       "fashion", ["footwear", "shoes", "sneakers", "boots"]),

    # ── AUTOMOTIVE ──
    ("car",            "automotive", ["car", "vehicle", "automobile", "auto"]),
    ("car_dealer",     "automotive", ["car dealer", "dealership", "auto dealer"]),
    ("rental_car",     "automotive", ["car rental", "vehicle rental", "hire car"]),
    ("repair",         "automotive", ["auto repair", "mechanic", "service center", "garage"]),
    ("electric_vehicle","automotive", ["electric vehicle", "ev", "tesla", "hybrid"]),
    ("transport",      "automotive", ["transport", "logistics", "freight", "trucking", "shipping"]),

    # ── ENERGY ──
    ("renewable",      "energy", ["renewable energy", "solar", "wind energy", "green energy"]),
    ("oil_gas",        "energy", ["oil", "gas", "petroleum", "energy sector"]),
    ("utility",        "energy", ["utility", "electricity", "power", "grid"]),

    # ── AGRICULTURE ──
    ("farming",        "agriculture", ["farming", "farm", "agriculture", "agricultural"]),
    ("livestock",      "agriculture", ["livestock", "animal husbandry", "poultry", "dairy"]),
    ("crop",           "agriculture", ["crop", "grain", "vegetable", "fruit", "plantation"]),
    ("organic_farm",   "agriculture", ["organic farming", "permaculture", "sustainable"]),
    ("agritech",       "agriculture", ["agritech", "precision farming", "smart farming"]),

    # ── LOGISTICS ──
    ("freight",        "logistics", ["freight", "cargo", "shipping", "logistics"]),
    ("warehouse",      "logistics", ["warehouse", "storage", "fulfillment center", "depot"]),
    ("customs",        "logistics", ["customs", "customs clearance", "brokerage", "import export"]),
    ("courier",        "logistics", ["courier", "delivery", "last mile", "express"]),

    # ── HR ──
    ("recruitment",    "hr", ["recruitment", "hiring", "staffing", "talent", "headhunter"]),
    ("hr_services",    "hr", ["hr", "human resources", "payroll", "benefits"]),
    ("training_hr",    "hr", ["corporate training", "employee training", "learning development"]),

    # ── MARKETING ──
    ("seo",            "marketing", ["seo", "search engine optimization", "google ranking"]),
    ("digital_marketing","marketing", ["digital marketing", "online marketing", "ppc", "sem"]),
    ("branding",       "marketing", ["branding", "brand identity", "logo design", "creative"]),
    ("email_marketing","marketing", ["email marketing", "newsletter", "campaign", "crm"]),
    ("market_research","marketing", ["market research", "survey", "focus group", "analytics"]),

    # ── CONSTRUCTION ──
    ("architect",      "construction", ["architect", "architecture", "design", "blueprint"]),
    ("contractor",     "construction", ["contractor", "builder", "construction company"]),
    ("interior",       "construction", ["interior design", "interior decorator", "renovation"]),
    ("civil_eng",      "construction", ["civil engineering", "structural", "infrastructure"]),

    # ── BEAUTY ──
    ("salon",          "beauty", ["salon", "hair salon", "barbershop", "hairdresser"]),
    ("skincare",       "beauty", ["skincare", "cosmetics", "beauty products", "makeup"]),
    ("spa_beauty",     "beauty", ["spa", "wellness center", "massage", "facial"]),
    ("nail",           "beauty", ["nail salon", "manicure", "pedicure"]),

    # ── EVENTS ──
    ("event_planning", "events", ["event planning", "event management", "event organizer"]),
    ("conference",     "events", ["conference", "congress", "summit", "seminar", "symposium"]),
    ("wedding",        "events", ["wedding", "wedding planner", "bridal"]),
    ("exhibition",     "events", ["exhibition", "trade show", "expo", "fair"]),
    ("entertainment_events", "events", ["entertainment", "show", "performance", "festival"]),

    # ── HOME & GARDEN ──
    ("furniture",      "home", ["furniture", "home furnishing", "interior"]),
    ("garden",         "home", ["garden", "landscaping", "gardening", "horticulture"]),
    ("cleaning",       "home", ["cleaning", "housekeeping", "janitorial", "maid service"]),
    ("security",       "home", ["security", "alarm", "cctv", "surveillance", "guard"]),

    # ── GAMING ──
    ("video_games",    "gaming", ["video game", "gaming", "console", "pc gaming"]),
    ("mobile_gaming",  "gaming", ["mobile game", "mobile gaming", "app game"]),
    ("game_dev",       "gaming", ["game developer", "game development", "game studio"]),
    ("esports_gaming", "gaming", ["esports", "competitive gaming", "tournament", "streamer"]),

    # ── NONPROFIT ──
    ("ngo",            "nonprofit", ["ngo", "nonprofit", "charity", "foundation", "association"]),
    ("volunteer",      "nonprofit", ["volunteer", "volunteering", "community service"]),
    ("donation",       "nonprofit", ["donation", "fundraising", "grant"]),

    # ── TELECOM ──
    ("telecom_op",     "telecom", ["telecom", "telecommunications", "mobile operator", "carrier"]),
    ("internet",       "telecom", ["internet", "isp", "broadband", "fiber", "wifi"]),

    # ── AEROSPACE ──
    ("aviation",       "aerospace", ["aviation", "aircraft", "airline", "airport", "aerospace"]),
    ("defense",        "aerospace", ["defense", "military", "security", "weapons"]),

    # ── GENERAL ──
    ("contact",        "general", ["contact", "email", "phone", "reach out", "enquiry", "inquiry"]),
    ("directory",      "general", ["directory", "listing", "database", "catalogue", "registry"]),
    ("association",    "general", ["association", "federation", "union", "chamber", "guild"]),
    ("certification",  "general", ["certification", "accreditation", "license", "credential"]),
    ("international",  "general", ["international", "global", "worldwide", "multinational"]),
    ("local",          "general", ["local", "regional", "domestic", "national"]),
    ("wholesale_gen",  "general", ["wholesale", "bulk", "trade"]),
    ("network",        "general", ["network", "networking", "community", "forum"]),
    ("research",       "general", ["research", "study", "report", "analysis", "data"]),
    ("news",           "general", ["news", "press", "media", "blog", "article"]),
]


# ──────────────────────────────────────────────────────────────────────────────
# TRANSLATION INDEX
# concept_id → { lang_code: [translated_terms] }
# ──────────────────────────────────────────────────────────────────────────────

TRANSLATIONS: dict[str, dict[str, list[str]]] = {

    # SPORTS
    "basketball": {
        "zh": ["篮球"], "zh_tw": ["籃球"], "ja": ["バスケットボール", "バスケ"],
        "ko": ["농구"], "de": ["Basketball"], "nl": ["basketbal"],
        "fr": ["basketball", "basket"], "es": ["baloncesto", "básquet"],
        "pt": ["basquete", "basquetebol"], "it": ["pallacanestro"],
        "ru": ["баскетбол"], "ar": ["كرة السلة"], "th": ["บาสเกตบอล"],
        "ms": ["bola keranjang"], "vi": ["bóng rổ"],
    },
    "football": {
        "zh": ["足球"], "zh_tw": ["足球"], "ja": ["サッカー", "フットボール"],
        "ko": ["축구"], "de": ["Fußball"], "nl": ["voetbal"],
        "fr": ["football", "foot"], "es": ["fútbol"], "pt": ["futebol"],
        "it": ["calcio"], "ru": ["футбол"], "ar": ["كرة القدم"],
        "th": ["ฟุตบอล"], "ms": ["bola sepak"], "vi": ["bóng đá"],
    },
    "golf": {
        "zh": ["高尔夫"], "zh_tw": ["高爾夫"], "ja": ["ゴルフ"],
        "ko": ["골프"], "de": ["Golf"], "nl": ["golf"],
        "fr": ["golf"], "es": ["golf"], "pt": ["golfe"],
        "it": ["golf"], "ru": ["гольф"], "ar": ["الغولف"],
        "th": ["กอล์ฟ"], "ms": ["golf"], "vi": ["golf"],
    },
    "tennis": {
        "zh": ["网球"], "zh_tw": ["網球"], "ja": ["テニス"],
        "ko": ["테니스"], "de": ["Tennis"], "nl": ["tennis"],
        "fr": ["tennis"], "es": ["tenis"], "pt": ["tênis"],
        "it": ["tennis"], "ru": ["теннис"], "ar": ["التنس"],
        "th": ["เทนนิส"], "ms": ["tenis"], "vi": ["quần vợt"],
    },
    "swimming": {
        "zh": ["游泳"], "zh_tw": ["游泳"], "ja": ["水泳", "スイミング"],
        "ko": ["수영"], "de": ["Schwimmen"], "nl": ["zwemmen"],
        "fr": ["natation"], "es": ["natación"], "pt": ["natação"],
        "it": ["nuoto"], "ru": ["плавание"], "ar": ["السباحة"],
        "th": ["ว่ายน้ำ"], "ms": ["renang"], "vi": ["bơi lội"],
    },
    "volleyball": {
        "zh": ["排球"], "zh_tw": ["排球"], "ja": ["バレーボール"],
        "ko": ["배구"], "de": ["Volleyball"], "nl": ["volleybal"],
        "fr": ["volleyball"], "es": ["voleibol"], "pt": ["vôlei"],
        "it": ["pallavolo"], "ru": ["волейбол"], "ar": ["الكرة الطائرة"],
        "th": ["วอลเลย์บอล"], "ms": ["bola voli"], "vi": ["bóng chuyền"],
    },
    "badminton": {
        "zh": ["羽毛球"], "zh_tw": ["羽毛球"], "ja": ["バドミントン"],
        "ko": ["배드민턴"], "de": ["Badminton"], "nl": ["badminton"],
        "fr": ["badminton"], "es": ["bádminton"], "pt": ["badminton"],
        "it": ["badminton"], "ru": ["бадминтон"], "ar": ["ريشة الطائرة"],
        "th": ["แบดมินตัน"], "ms": ["badminton"], "vi": ["cầu lông"],
    },
    "baseball": {
        "zh": ["棒球"], "zh_tw": ["棒球"], "ja": ["野球", "ベースボール"],
        "ko": ["야구"], "de": ["Baseball"], "nl": ["honkbal"],
        "fr": ["baseball"], "es": ["béisbol"], "pt": ["beisebol"],
        "it": ["baseball"], "ru": ["бейсбол"], "ar": ["بيسبول"],
        "th": ["เบสบอล"], "ms": ["besbol"], "vi": ["bóng chày"],
    },
    "rugby": {
        "zh": ["橄榄球"], "zh_tw": ["橄欖球"], "ja": ["ラグビー"],
        "ko": ["럭비"], "de": ["Rugby"], "nl": ["rugby"],
        "fr": ["rugby"], "es": ["rugby"], "pt": ["rugby"],
        "it": ["rugby"], "ru": ["регби"], "ar": ["الرغبي"],
        "th": ["รักบี้"], "ms": ["ragbi"], "vi": ["bóng bầu dục"],
    },
    "cycling": {
        "zh": ["骑行", "自行车"], "zh_tw": ["騎行", "單車"],
        "ja": ["サイクリング", "自転車"], "ko": ["사이클링", "자전거"],
        "de": ["Radfahren", "Radsport"], "nl": ["fietsen", "wielrennen"],
        "fr": ["cyclisme", "vélo"], "es": ["ciclismo", "bicicleta"],
        "pt": ["ciclismo", "bicicleta"], "it": ["ciclismo", "bici"],
        "ru": ["велоспорт", "велосипед"], "ar": ["ركوب الدراجات"],
        "th": ["จักรยาน"], "ms": ["berbasikal"], "vi": ["đua xe đạp"],
    },
    "martial_arts": {
        "zh": ["武术", "格斗"], "zh_tw": ["武術", "格鬥"],
        "ja": ["武道", "格闘技", "空手"], "ko": ["무술", "태권도"],
        "de": ["Kampfsport", "Kampfkunst"], "nl": ["vechtsporten"],
        "fr": ["arts martiaux"], "es": ["artes marciales"],
        "pt": ["artes marciais"], "it": ["arti marziali"],
        "ru": ["единоборства", "боевые искусства"], "ar": ["فنون القتال"],
        "th": ["ศิลปะการต่อสู้", "มวยไทย"], "ms": ["seni bela diri"], "vi": ["võ thuật"],
    },
    "fitness": {
        "zh": ["健身", "锻炼"], "zh_tw": ["健身"], "ja": ["フィットネス", "トレーニング"],
        "ko": ["피트니스", "헬스"], "de": ["Fitness", "Fitnessstudio"],
        "nl": ["fitness", "sportschool"], "fr": ["fitness", "salle de sport"],
        "es": ["fitness", "gimnasio"], "pt": ["academia", "fitness"],
        "it": ["fitness", "palestra"], "ru": ["фитнес", "спортзал"],
        "ar": ["لياقة بدنية", "صالة رياضية"], "th": ["ฟิตเนส"],
        "ms": ["kecergasan"], "vi": ["thể dục", "phòng gym"],
    },
    "yoga": {
        "zh": ["瑜伽"], "zh_tw": ["瑜伽"], "ja": ["ヨガ"],
        "ko": ["요가"], "de": ["Yoga"], "nl": ["yoga"],
        "fr": ["yoga"], "es": ["yoga"], "pt": ["yoga"],
        "it": ["yoga"], "ru": ["йога"], "ar": ["اليوغا"],
        "th": ["โยคะ"], "ms": ["yoga"], "vi": ["yoga"],
    },
    "sports_camp": {
        "zh": ["运动夏令营", "体育营"], "zh_tw": ["運動夏令營"],
        "ja": ["スポーツキャンプ", "サマーキャンプ"], "ko": ["스포츠 캠프", "여름 캠프"],
        "de": ["Sportcamp", "Sommercamp"], "nl": ["sportskamp", "zomerkamp"],
        "fr": ["camp sportif", "camp d'été"], "es": ["campamento deportivo", "campamento de verano"],
        "pt": ["acampamento esportivo", "acampamento de verão"], "it": ["camp sportivo", "camp estivo"],
        "ru": ["спортивный лагерь", "летний лагерь"], "ar": ["مخيم رياضي", "مخيم صيفي"],
        "th": ["ค่ายกีฬา", "ค่ายฤดูร้อน"], "ms": ["kem sukan", "kem musim panas"],
        "vi": ["trại thể thao", "trại hè"],
    },
    "sports_academy": {
        "zh": ["体育学院", "运动学院"], "zh_tw": ["體育學院"],
        "ja": ["スポーツアカデミー", "スポーツスクール"], "ko": ["스포츠 아카데미"],
        "de": ["Sportakademie", "Sportschule"], "nl": ["sportacademie"],
        "fr": ["académie sportive", "école de sport"], "es": ["academia deportiva"],
        "pt": ["academia esportiva"], "it": ["accademia sportiva"],
        "ru": ["спортивная академия"], "ar": ["أكاديمية رياضية"],
        "th": ["อคาเดมีกีฬา"], "ms": ["akademi sukan"], "vi": ["học viện thể thao"],
    },
    "coach": {
        "zh": ["教练"], "zh_tw": ["教練"], "ja": ["コーチ", "指導者"],
        "ko": ["코치", "감독"], "de": ["Trainer", "Coach"],
        "nl": ["trainer", "coach"], "fr": ["entraîneur", "coach"],
        "es": ["entrenador", "coach"], "pt": ["treinador"],
        "it": ["allenatore", "coach"], "ru": ["тренер"],
        "ar": ["مدرب", "مدرّب رياضي"], "th": ["โค้ช", "ผู้ฝึกสอน"],
        "ms": ["jurulatih"], "vi": ["huấn luyện viên"],
    },
    "tournament": {
        "zh": ["锦标赛", "比赛"], "zh_tw": ["錦標賽", "賽事"],
        "ja": ["トーナメント", "大会", "選手権"], "ko": ["토너먼트", "대회"],
        "de": ["Turnier", "Meisterschaft"], "nl": ["toernooi", "kampioenschap"],
        "fr": ["tournoi", "championnat"], "es": ["torneo", "campeonato"],
        "pt": ["torneio", "campeonato"], "it": ["torneo", "campionato"],
        "ru": ["турнир", "чемпионат"], "ar": ["بطولة", "دوري"],
        "th": ["ทัวร์นาเมนต์", "การแข่งขัน"], "ms": ["kejohanan"], "vi": ["giải đấu"],
    },
    "athlete": {
        "zh": ["运动员", "青少年运动员"], "zh_tw": ["運動員"],
        "ja": ["アスリート", "選手", "ジュニア"], "ko": ["선수", "유스"],
        "de": ["Athlet", "Sportler", "Jugend"], "nl": ["atleet", "sporter"],
        "fr": ["athlète", "sportif", "jeune"], "es": ["atleta", "deportista", "joven"],
        "pt": ["atleta", "esportista"], "it": ["atleta", "sportivo"],
        "ru": ["атлет", "спортсмен", "молодёжь"], "ar": ["رياضي", "لاعب"],
        "th": ["นักกีฬา", "นักกีฬาเยาวชน"], "ms": ["atlet"], "vi": ["vận động viên"],
    },
    "sports_agent": {
        "zh": ["体育代理", "运动代理商"], "zh_tw": ["體育代理"],
        "ja": ["スポーツエージェント"], "ko": ["스포츠 에이전트"],
        "de": ["Sportvermarkter", "Agent"], "nl": ["sportagent"],
        "fr": ["agent sportif"], "es": ["agente deportivo"],
        "pt": ["agente esportivo"], "it": ["agente sportivo"],
        "ru": ["спортивный агент"], "ar": ["وكيل رياضي"],
        "th": ["ตัวแทนนักกีฬา"], "ms": ["ejen sukan"], "vi": ["đại lý thể thao"],
    },

    # TRAVEL
    "travel_agency": {
        "zh": ["旅行社", "旅游公司"], "zh_tw": ["旅行社"],
        "ja": ["旅行代理店", "旅行会社"], "ko": ["여행사", "여행 대리점"],
        "de": ["Reisebüro", "Reiseveranstalter"], "nl": ["reisbureau", "touroperator"],
        "fr": ["agence de voyage", "voyagiste"], "es": ["agencia de viajes", "tour operador"],
        "pt": ["agência de viagens", "operadora de turismo"], "it": ["agenzia di viaggi", "tour operator"],
        "ru": ["туристическое агентство", "турагентство"], "ar": ["وكالة سفر", "شركة سياحة"],
        "th": ["บริษัทท่องเที่ยว", "เอเจนซี่ท่องเที่ยว"],
        "ms": ["agen perjalanan", "syarikat pelancongan"], "vi": ["công ty du lịch", "đại lý du lịch"],
    },
    "tour": {
        "zh": ["旅游", "旅行", "导游"], "zh_tw": ["旅遊", "旅行"],
        "ja": ["ツアー", "旅行", "観光"], "ko": ["투어", "여행", "관광"],
        "de": ["Tour", "Reise", "Ausflug"], "nl": ["tour", "reis", "uitstap"],
        "fr": ["circuit", "voyage", "excursion"], "es": ["tour", "viaje", "excursión"],
        "pt": ["tour", "viagem", "excursão"], "it": ["tour", "viaggio", "gita"],
        "ru": ["тур", "путешествие", "экскурсия"], "ar": ["جولة", "رحلة سياحية"],
        "th": ["ทัวร์", "การท่องเที่ยว"], "ms": ["lawatan", "pelancongan"], "vi": ["tour", "du lịch"],
    },
    "hotel": {
        "zh": ["酒店", "宾馆", "住宿"], "zh_tw": ["酒店", "飯店"],
        "ja": ["ホテル", "旅館", "宿泊"], "ko": ["호텔", "숙박"],
        "de": ["Hotel", "Unterkunft", "Herberge"], "nl": ["hotel", "accommodatie"],
        "fr": ["hôtel", "hébergement", "logement"], "es": ["hotel", "alojamiento", "hospedaje"],
        "pt": ["hotel", "hospedagem", "acomodação"], "it": ["hotel", "alloggio", "struttura"],
        "ru": ["отель", "гостиница", "жильё"], "ar": ["فندق", "إقامة"],
        "th": ["โรงแรม", "ที่พัก"], "ms": ["hotel", "penginapan"], "vi": ["khách sạn", "lưu trú"],
    },
    "booking": {
        "zh": ["预订", "预定"], "zh_tw": ["預訂"],
        "ja": ["予約", "ブッキング"], "ko": ["예약"],
        "de": ["Buchung", "Reservierung"], "nl": ["boeking", "reservering"],
        "fr": ["réservation"], "es": ["reserva", "reservación"],
        "pt": ["reserva"], "it": ["prenotazione"],
        "ru": ["бронирование", "заказ"], "ar": ["حجز"],
        "th": ["จอง", "การจอง"], "ms": ["tempahan"], "vi": ["đặt chỗ", "đặt phòng"],
    },
    "adventure": {
        "zh": ["探险", "户外", "冒险"], "zh_tw": ["探險", "戶外"],
        "ja": ["アドベンチャー", "アウトドア", "冒険"], "ko": ["어드벤처", "야외"],
        "de": ["Abenteuer", "Outdoor"], "nl": ["avontuur", "outdoor"],
        "fr": ["aventure", "plein air"], "es": ["aventura", "al aire libre"],
        "pt": ["aventura", "ao ar livre"], "it": ["avventura", "outdoor"],
        "ru": ["приключение", "активный отдых"], "ar": ["مغامرة", "الهواء الطلق"],
        "th": ["การผจญภัย", "กลางแจ้ง"], "ms": ["pengembaraan", "luar"], "vi": ["phiêu lưu", "ngoài trời"],
    },
    "travel_package": {
        "zh": ["旅游套餐", "度假套餐"], "zh_tw": ["旅遊套餐"],
        "ja": ["旅行パッケージ", "パックツアー"], "ko": ["여행 패키지", "패키지 여행"],
        "de": ["Reisepaket", "Pauschalreise"], "nl": ["reispakket", "pakketreis"],
        "fr": ["forfait voyage", "tout compris"], "es": ["paquete turístico", "todo incluido"],
        "pt": ["pacote turístico"], "it": ["pacchetto viaggio"],
        "ru": ["турпакет", "пакетный тур"], "ar": ["باقة سياحية"],
        "th": ["แพ็คเกจท่องเที่ยว"], "ms": ["pakej pelancongan"], "vi": ["gói du lịch"],
    },

    # FOOD
    "restaurant": {
        "zh": ["餐厅", "饭店", "餐馆"], "zh_tw": ["餐廳", "飯館"],
        "ja": ["レストラン", "飲食店"], "ko": ["레스토랑", "식당"],
        "de": ["Restaurant", "Gaststätte"], "nl": ["restaurant"],
        "fr": ["restaurant"], "es": ["restaurante"],
        "pt": ["restaurante"], "it": ["ristorante"],
        "ru": ["ресторан", "кафе"], "ar": ["مطعم"],
        "th": ["ร้านอาหาร"], "ms": ["restoran"], "vi": ["nhà hàng"],
    },
    "cafe": {
        "zh": ["咖啡店", "咖啡馆"], "zh_tw": ["咖啡廳"],
        "ja": ["カフェ", "喫茶店"], "ko": ["카페", "커피숍"],
        "de": ["Café", "Kaffeehaus"], "nl": ["café", "koffiehuis"],
        "fr": ["café", "brasserie"], "es": ["café", "cafetería"],
        "pt": ["café", "cafeteria"], "it": ["bar", "caffè"],
        "ru": ["кафе"], "ar": ["مقهى"],
        "th": ["คาเฟ่"], "ms": ["kafe"], "vi": ["quán cà phê"],
    },
    "catering": {
        "zh": ["餐饮", "餐饮服务", "外卖服务"], "zh_tw": ["餐飲服務"],
        "ja": ["ケータリング", "仕出し"], "ko": ["케이터링"],
        "de": ["Catering", "Veranstaltungsservice"], "nl": ["catering"],
        "fr": ["traiteur", "restauration"], "es": ["catering", "servicio de alimentación"],
        "pt": ["catering", "buffet"], "it": ["catering"],
        "ru": ["кейтеринг"], "ar": ["خدمة تقديم الطعام"],
        "th": ["จัดเลี้ยง"], "ms": ["katering"], "vi": ["dịch vụ ăn uống"],
    },
    "food_supplier": {
        "zh": ["食品供应商", "食材供应"], "zh_tw": ["食品供應商"],
        "ja": ["食品サプライヤー", "食品問屋"], "ko": ["식품 공급업체"],
        "de": ["Lebensmittellieferant", "Großhändler"], "nl": ["voedselleverancier"],
        "fr": ["fournisseur alimentaire", "grossiste"], "es": ["proveedor de alimentos"],
        "pt": ["fornecedor de alimentos"], "it": ["fornitore alimentare"],
        "ru": ["поставщик продуктов питания"], "ar": ["مورد غذائي"],
        "th": ["ผู้จำหน่ายอาหาร"], "ms": ["pembekal makanan"], "vi": ["nhà cung cấp thực phẩm"],
    },

    # TECHNOLOGY
    "software": {
        "zh": ["软件", "应用程序", "平台"], "zh_tw": ["軟體", "平台"],
        "ja": ["ソフトウェア", "アプリ", "プラットフォーム"], "ko": ["소프트웨어", "앱", "플랫폼"],
        "de": ["Software", "Anwendung", "Plattform"], "nl": ["software", "applicatie"],
        "fr": ["logiciel", "application", "plateforme"], "es": ["software", "aplicación", "plataforma"],
        "pt": ["software", "aplicativo", "plataforma"], "it": ["software", "applicazione"],
        "ru": ["программное обеспечение", "приложение"], "ar": ["برنامج", "تطبيق"],
        "th": ["ซอฟต์แวร์", "แอปพลิเคชัน"], "ms": ["perisian", "aplikasi"], "vi": ["phần mềm", "ứng dụng"],
    },
    "ai": {
        "zh": ["人工智能", "AI", "机器学习"], "zh_tw": ["人工智慧", "AI"],
        "ja": ["人工知能", "AI", "機械学習"], "ko": ["인공지능", "AI", "머신러닝"],
        "de": ["künstliche Intelligenz", "KI", "Machine Learning"], "nl": ["kunstmatige intelligentie", "AI"],
        "fr": ["intelligence artificielle", "IA"], "es": ["inteligencia artificial", "IA"],
        "pt": ["inteligência artificial", "IA"], "it": ["intelligenza artificiale", "IA"],
        "ru": ["искусственный интеллект", "ИИ"], "ar": ["الذكاء الاصطناعي"],
        "th": ["ปัญญาประดิษฐ์", "AI"], "ms": ["kecerdasan buatan", "AI"], "vi": ["trí tuệ nhân tạo", "AI"],
    },
    "cybersecurity": {
        "zh": ["网络安全", "信息安全"], "zh_tw": ["網路安全", "資訊安全"],
        "ja": ["サイバーセキュリティ", "情報セキュリティ"], "ko": ["사이버보안", "정보보안"],
        "de": ["Cybersicherheit", "IT-Sicherheit"], "nl": ["cybersecurity", "informatiebeveiliging"],
        "fr": ["cybersécurité", "sécurité informatique"], "es": ["ciberseguridad", "seguridad informática"],
        "pt": ["segurança cibernética", "segurança da informação"], "it": ["sicurezza informatica"],
        "ru": ["кибербезопасность", "информационная безопасность"], "ar": ["الأمن السيبراني"],
        "th": ["ความปลอดภัยทางไซเบอร์"], "ms": ["keselamatan siber"], "vi": ["an ninh mạng"],
    },
    "cloud": {
        "zh": ["云计算", "云服务"], "zh_tw": ["雲端服務", "雲端運算"],
        "ja": ["クラウド", "クラウドコンピューティング"], "ko": ["클라우드", "클라우드 컴퓨팅"],
        "de": ["Cloud", "Cloud-Computing"], "nl": ["cloud", "cloud computing"],
        "fr": ["cloud", "informatique en nuage"], "es": ["nube", "computación en la nube"],
        "pt": ["nuvem", "computação em nuvem"], "it": ["cloud", "computazione cloud"],
        "ru": ["облако", "облачные вычисления"], "ar": ["الحوسبة السحابية"],
        "th": ["คลาวด์"], "ms": ["awan", "komputeran awan"], "vi": ["điện toán đám mây"],
    },
    "startup": {
        "zh": ["创业公司", "初创企业"], "zh_tw": ["新創公司", "新創企業"],
        "ja": ["スタートアップ", "ベンチャー企業"], "ko": ["스타트업", "벤처"],
        "de": ["Startup", "Jungunternehmen"], "nl": ["startup"],
        "fr": ["startup", "jeune pousse"], "es": ["startup", "empresa emergente"],
        "pt": ["startup"], "it": ["startup"],
        "ru": ["стартап"], "ar": ["شركة ناشئة"],
        "th": ["สตาร์ทอัพ"], "ms": ["syarikat permulaan", "startup"], "vi": ["khởi nghiệp", "startup"],
    },

    # BUSINESS
    "company": {
        "zh": ["公司", "企业"], "zh_tw": ["公司", "企業"],
        "ja": ["会社", "企業", "法人"], "ko": ["회사", "기업"],
        "de": ["Unternehmen", "Firma", "GmbH"], "nl": ["bedrijf", "onderneming"],
        "fr": ["entreprise", "société", "compagnie"], "es": ["empresa", "compañía", "sociedad"],
        "pt": ["empresa", "companhia"], "it": ["azienda", "impresa", "società"],
        "ru": ["компания", "предприятие", "организация"], "ar": ["شركة", "مؤسسة"],
        "th": ["บริษัท", "องค์กร"], "ms": ["syarikat", "perusahaan"], "vi": ["công ty", "doanh nghiệp"],
    },
    "supplier": {
        "zh": ["供应商", "厂商"], "zh_tw": ["供應商", "廠商"],
        "ja": ["サプライヤー", "メーカー", "卸売業者"], "ko": ["공급업체", "납품업체"],
        "de": ["Lieferant", "Zulieferer", "Hersteller"], "nl": ["leverancier"],
        "fr": ["fournisseur", "fabricant"], "es": ["proveedor", "fabricante"],
        "pt": ["fornecedor", "fabricante"], "it": ["fornitore", "produttore"],
        "ru": ["поставщик", "производитель"], "ar": ["مورد", "مصنّع"],
        "th": ["ผู้จัดจำหน่าย", "ผู้ผลิต"], "ms": ["pembekal", "pengeluar"], "vi": ["nhà cung cấp", "nhà sản xuất"],
    },
    "consulting": {
        "zh": ["咨询", "顾问"], "zh_tw": ["諮詢", "顧問"],
        "ja": ["コンサルティング", "コンサルタント", "顧問"], "ko": ["컨설팅", "컨설턴트"],
        "de": ["Beratung", "Unternehmensberatung", "Berater"], "nl": ["advies", "consultancy"],
        "fr": ["conseil", "consulting", "consultant"], "es": ["consultoría", "asesoría"],
        "pt": ["consultoria", "assessoria"], "it": ["consulenza", "consulente"],
        "ru": ["консалтинг", "консультирование"], "ar": ["استشارات", "مستشار"],
        "th": ["ที่ปรึกษา", "คอนซัลติ้ง"], "ms": ["perundingan", "konsultan"], "vi": ["tư vấn", "tư vấn doanh nghiệp"],
    },
    "import_export": {
        "zh": ["进出口", "贸易", "国际贸易"], "zh_tw": ["進出口", "貿易"],
        "ja": ["輸入", "輸出", "貿易"], "ko": ["수입", "수출", "무역"],
        "de": ["Import", "Export", "Handel"], "nl": ["import", "export", "handel"],
        "fr": ["import", "export", "commerce international"], "es": ["importación", "exportación", "comercio"],
        "pt": ["importação", "exportação", "comércio"], "it": ["import", "export", "commercio"],
        "ru": ["импорт", "экспорт", "торговля"], "ar": ["استيراد", "تصدير", "تجارة"],
        "th": ["นำเข้า", "ส่งออก", "การค้า"], "ms": ["import", "eksport", "perdagangan"], "vi": ["nhập khẩu", "xuất khẩu", "thương mại"],
    },
    "services": {
        "zh": ["服务", "服务提供商"], "zh_tw": ["服務", "服務商"],
        "ja": ["サービス", "サービス提供者"], "ko": ["서비스", "용역"],
        "de": ["Dienstleistung", "Service"], "nl": ["dienst", "dienstverlening"],
        "fr": ["service", "prestataire"], "es": ["servicio", "prestación"],
        "pt": ["serviço", "prestador"], "it": ["servizio", "prestazione"],
        "ru": ["услуга", "сервис"], "ar": ["خدمة", "مزود خدمة"],
        "th": ["บริการ"], "ms": ["perkhidmatan"], "vi": ["dịch vụ"],
    },
    "procurement": {
        "zh": ["采购", "招标"], "zh_tw": ["採購", "招標"],
        "ja": ["調達", "購買", "入札"], "ko": ["조달", "구매"],
        "de": ["Beschaffung", "Einkauf", "Ausschreibung"], "nl": ["inkoop", "aanbesteding"],
        "fr": ["approvisionnement", "achat", "appel d'offres"], "es": ["aprovisionamiento", "compra", "licitación"],
        "pt": ["aquisição", "compra"], "it": ["approvvigionamento", "acquisto"],
        "ru": ["закупка", "снабжение"], "ar": ["المشتريات", "التوريد"],
        "th": ["การจัดซื้อ"], "ms": ["perolehan", "pembelian"], "vi": ["mua sắm", "đấu thầu"],
    },

    # FINANCE
    "bank": {
        "zh": ["银行", "金融机构"], "zh_tw": ["銀行", "金融機構"],
        "ja": ["銀行", "金融機関"], "ko": ["은행", "금융기관"],
        "de": ["Bank", "Kreditinstitut"], "nl": ["bank"],
        "fr": ["banque"], "es": ["banco"],
        "pt": ["banco"], "it": ["banca"],
        "ru": ["банк"], "ar": ["بنك", "مصرف"],
        "th": ["ธนาคาร"], "ms": ["bank"], "vi": ["ngân hàng"],
    },
    "investment": {
        "zh": ["投资", "基金"], "zh_tw": ["投資", "基金"],
        "ja": ["投資", "ファンド"], "ko": ["투자", "펀드"],
        "de": ["Investition", "Anlage", "Fonds"], "nl": ["investering", "fonds"],
        "fr": ["investissement", "fonds"], "es": ["inversión", "fondo"],
        "pt": ["investimento", "fundo"], "it": ["investimento", "fondo"],
        "ru": ["инвестиции", "фонд"], "ar": ["استثمار", "صندوق"],
        "th": ["การลงทุน", "กองทุน"], "ms": ["pelaburan", "dana"], "vi": ["đầu tư", "quỹ"],
    },
    "accounting": {
        "zh": ["会计", "审计", "税务"], "zh_tw": ["會計", "審計"],
        "ja": ["会計", "経理", "税務"], "ko": ["회계", "세무"],
        "de": ["Buchhaltung", "Steuer", "Wirtschaftsprüfung"], "nl": ["boekhouding", "accountancy"],
        "fr": ["comptabilité", "audit", "fiscalité"], "es": ["contabilidad", "auditoría", "impuesto"],
        "pt": ["contabilidade", "auditoria"], "it": ["contabilità", "revisione"],
        "ru": ["бухгалтерия", "аудит", "налоги"], "ar": ["محاسبة", "مراجعة حسابات"],
        "th": ["บัญชี", "ภาษี"], "ms": ["perakaunan", "cukai"], "vi": ["kế toán", "kiểm toán"],
    },
    "fintech": {
        "zh": ["金融科技", "支付", "移动支付"], "zh_tw": ["金融科技", "支付"],
        "ja": ["フィンテック", "決済"], "ko": ["핀테크", "결제"],
        "de": ["Fintech", "Zahlungsdienstleister"], "nl": ["fintech", "betaling"],
        "fr": ["fintech", "paiement"], "es": ["fintech", "pago"],
        "pt": ["fintech", "pagamento"], "it": ["fintech", "pagamento"],
        "ru": ["финтех", "платёжные услуги"], "ar": ["التكنولوجيا المالية", "الدفع"],
        "th": ["ฟินเทค", "การชำระเงิน"], "ms": ["teknologi kewangan"], "vi": ["fintech", "thanh toán"],
    },

    # EDUCATION
    "school": {
        "zh": ["学校", "中学", "小学"], "zh_tw": ["學校", "中學"],
        "ja": ["学校", "中学校", "高校"], "ko": ["학교", "중학교", "고등학교"],
        "de": ["Schule", "Gymnasium"], "nl": ["school", "middelbare school"],
        "fr": ["école", "lycée", "collège"], "es": ["colegio", "escuela", "instituto"],
        "pt": ["escola", "colégio"], "it": ["scuola", "istituto"],
        "ru": ["школа", "гимназия"], "ar": ["مدرسة"],
        "th": ["โรงเรียน"], "ms": ["sekolah"], "vi": ["trường học", "trường"],
    },
    "university": {
        "zh": ["大学", "高校"], "zh_tw": ["大學", "大專"],
        "ja": ["大学", "大学院"], "ko": ["대학교", "대학원"],
        "de": ["Universität", "Hochschule"], "nl": ["universiteit", "hogeschool"],
        "fr": ["université", "école supérieure"], "es": ["universidad", "facultad"],
        "pt": ["universidade", "faculdade"], "it": ["università", "ateneo"],
        "ru": ["университет", "вуз"], "ar": ["جامعة"],
        "th": ["มหาวิทยาลัย"], "ms": ["universiti"], "vi": ["trường đại học", "đại học"],
    },
    "online_edu": {
        "zh": ["在线学习", "网课", "远程教育"], "zh_tw": ["線上學習", "遠距教育"],
        "ja": ["オンライン学習", "eラーニング", "遠隔教育"], "ko": ["온라인 학습", "이러닝"],
        "de": ["Online-Lernen", "E-Learning", "Fernunterricht"], "nl": ["online leren", "e-learning"],
        "fr": ["apprentissage en ligne", "e-learning", "formation à distance"],
        "es": ["aprendizaje en línea", "e-learning", "educación a distancia"],
        "pt": ["aprendizado online", "e-learning"], "it": ["apprendimento online", "e-learning"],
        "ru": ["онлайн-обучение", "дистанционное образование"], "ar": ["التعلم الإلكتروني", "التعليم عن بعد"],
        "th": ["เรียนออนไลน์"], "ms": ["pembelajaran dalam talian"], "vi": ["học trực tuyến", "e-learning"],
    },
    "international_school": {
        "zh": ["国际学校"], "zh_tw": ["國際學校"],
        "ja": ["インターナショナルスクール"], "ko": ["국제학교"],
        "de": ["internationale Schule"], "nl": ["internationale school"],
        "fr": ["école internationale"], "es": ["escuela internacional"],
        "pt": ["escola internacional"], "it": ["scuola internazionale"],
        "ru": ["международная школа"], "ar": ["مدرسة دولية"],
        "th": ["โรงเรียนนานาชาติ"], "ms": ["sekolah antarabangsa"], "vi": ["trường quốc tế"],
    },
    "language_school": {
        "zh": ["语言学校", "语言培训"], "zh_tw": ["語言學校", "語言培訓"],
        "ja": ["語学学校", "語学学院"], "ko": ["어학원", "언어 학교"],
        "de": ["Sprachschule", "Sprachkurs"], "nl": ["taalschool"],
        "fr": ["école de langues", "cours de langue"], "es": ["escuela de idiomas"],
        "pt": ["escola de idiomas"], "it": ["scuola di lingue"],
        "ru": ["языковая школа", "курсы языков"], "ar": ["مدرسة اللغات"],
        "th": ["โรงเรียนสอนภาษา"], "ms": ["sekolah bahasa"], "vi": ["trường ngoại ngữ"],
    },
    "tutoring": {
        "zh": ["辅导", "家教"], "zh_tw": ["補習", "家教"],
        "ja": ["個別指導", "家庭教師"], "ko": ["과외", "개인 지도"],
        "de": ["Nachhilfe", "Privatunterricht"], "nl": ["bijles", "privéles"],
        "fr": ["soutien scolaire", "cours particulier"], "es": ["tutoría", "clases particulares"],
        "pt": ["tutoria", "aulas particulares"], "it": ["tutoraggio", "lezioni private"],
        "ru": ["репетитор", "частные уроки"], "ar": ["دروس خصوصية", "مدرس خاص"],
        "th": ["สอนพิเศษ", "ติวเตอร์"], "ms": ["tuisyen"], "vi": ["gia sư", "dạy kèm"],
    },

    # HEALTH
    "hospital": {
        "zh": ["医院", "诊所", "医疗机构"], "zh_tw": ["醫院", "診所"],
        "ja": ["病院", "クリニック", "医療機関"], "ko": ["병원", "의원", "의료기관"],
        "de": ["Krankenhaus", "Klinik", "Arztpraxis"], "nl": ["ziekenhuis", "kliniek"],
        "fr": ["hôpital", "clinique", "établissement médical"], "es": ["hospital", "clínica", "centro médico"],
        "pt": ["hospital", "clínica", "centro médico"], "it": ["ospedale", "clinica"],
        "ru": ["больница", "клиника", "медицинское учреждение"], "ar": ["مستشفى", "عيادة"],
        "th": ["โรงพยาบาล", "คลินิก"], "ms": ["hospital", "klinik"], "vi": ["bệnh viện", "phòng khám"],
    },
    "wellness": {
        "zh": ["健康", "养生", "康健", "水疗"], "zh_tw": ["健康", "養生", "水療"],
        "ja": ["ウェルネス", "スパ", "マッサージ"], "ko": ["웰니스", "스파", "마사지"],
        "de": ["Wellness", "Spa", "Massage"], "nl": ["wellness", "spa"],
        "fr": ["bien-être", "spa", "massage"], "es": ["bienestar", "spa", "masaje"],
        "pt": ["bem-estar", "spa", "massagem"], "it": ["benessere", "spa", "massaggio"],
        "ru": ["оздоровление", "спа", "массаж"], "ar": ["رعاية صحية", "سبا", "مساج"],
        "th": ["สุขภาพ", "สปา", "นวด"], "ms": ["kesihatan", "spa", "urutan"], "vi": ["sức khỏe", "spa", "massage"],
    },
    "dental": {
        "zh": ["牙科", "口腔"], "zh_tw": ["牙科", "口腔"],
        "ja": ["歯科", "歯医者"], "ko": ["치과"],
        "de": ["Zahnarzt", "Zahnklinik"], "nl": ["tandarts", "tandheelkunde"],
        "fr": ["dentiste", "chirurgien dentiste"], "es": ["dentista", "clínica dental"],
        "pt": ["dentista", "odontologia"], "it": ["dentista", "odontoiatria"],
        "ru": ["стоматолог", "зубная клиника"], "ar": ["طب الأسنان", "طبيب أسنان"],
        "th": ["ทันตกรรม", "หมอฟัน"], "ms": ["pergigian", "doktor gigi"], "vi": ["nha khoa", "bác sĩ răng"],
    },

    # LEGAL
    "law_firm": {
        "zh": ["律师事务所", "律师"], "zh_tw": ["律師事務所", "律師"],
        "ja": ["法律事務所", "弁護士"], "ko": ["법무법인", "변호사"],
        "de": ["Anwaltskanzlei", "Rechtsanwalt"], "nl": ["advocatenkantoor", "advocaat"],
        "fr": ["cabinet d'avocat", "avocat"], "es": ["bufete de abogados", "abogado"],
        "pt": ["escritório de advocacia", "advogado"], "it": ["studio legale", "avvocato"],
        "ru": ["юридическая фирма", "адвокат"], "ar": ["مكتب محاماة", "محامٍ"],
        "th": ["สำนักงานกฎหมาย", "ทนายความ"], "ms": ["firma guaman", "peguam"], "vi": ["công ty luật", "luật sư"],
    },
    "compliance": {
        "zh": ["合规", "监管", "法规"], "zh_tw": ["合規", "監管"],
        "ja": ["コンプライアンス", "規制"], "ko": ["컴플라이언스", "규제"],
        "de": ["Compliance", "Regulierung"], "nl": ["compliance", "naleving"],
        "fr": ["conformité", "réglementation"], "es": ["cumplimiento", "regulación"],
        "pt": ["conformidade", "regulamentação"], "it": ["conformità", "regolamentazione"],
        "ru": ["комплаенс", "соответствие требованиям"], "ar": ["الامتثال", "التنظيم"],
        "th": ["การปฏิบัติตามกฎระเบียบ"], "ms": ["pematuhan"], "vi": ["tuân thủ", "quy định"],
    },

    # REAL ESTATE
    "property": {
        "zh": ["房产", "不动产", "物业"], "zh_tw": ["房產", "不動產", "物業"],
        "ja": ["不動産", "物件"], "ko": ["부동산", "물건"],
        "de": ["Immobilien", "Grundstück", "Eigentum"], "nl": ["vastgoed", "woning"],
        "fr": ["immobilier", "bien immobilier"], "es": ["inmueble", "propiedad", "bienes raíces"],
        "pt": ["imóvel", "propriedade", "imobiliária"], "it": ["immobile", "proprietà"],
        "ru": ["недвижимость", "объект"], "ar": ["عقار", "ملكية"],
        "th": ["อสังหาริมทรัพย์", "ทรัพย์สิน"], "ms": ["hartanah", "harta"], "vi": ["bất động sản", "tài sản"],
    },
    "rental": {
        "zh": ["租赁", "出租", "租房"], "zh_tw": ["租賃", "出租"],
        "ja": ["賃貸", "レンタル", "貸し"], "ko": ["임대", "렌탈"],
        "de": ["Miete", "Vermietung", "Leasing"], "nl": ["huur", "verhuur"],
        "fr": ["location", "loyer"], "es": ["alquiler", "arrendamiento"],
        "pt": ["aluguel", "arrendamento"], "it": ["affitto", "locazione"],
        "ru": ["аренда", "сдача в аренду"], "ar": ["إيجار", "استئجار"],
        "th": ["เช่า", "ให้เช่า"], "ms": ["sewa", "sewaan"], "vi": ["thuê", "cho thuê"],
    },

    # RETAIL
    "ecommerce": {
        "zh": ["电商", "网购", "在线购物"], "zh_tw": ["電商", "網購"],
        "ja": ["ECサイト", "ネットショッピング", "オンラインショップ"], "ko": ["이커머스", "온라인쇼핑"],
        "de": ["E-Commerce", "Online-Shop", "Versandhandel"], "nl": ["e-commerce", "webwinkel"],
        "fr": ["e-commerce", "boutique en ligne"], "es": ["e-commerce", "tienda online"],
        "pt": ["e-commerce", "loja virtual"], "it": ["e-commerce", "negozio online"],
        "ru": ["электронная коммерция", "интернет-магазин"], "ar": ["التجارة الإلكترونية", "متجر إلكتروني"],
        "th": ["อีคอมเมิร์ซ", "ร้านค้าออนไลน์"], "ms": ["e-dagang", "kedai online"], "vi": ["thương mại điện tử", "cửa hàng trực tuyến"],
    },
    "wholesale": {
        "zh": ["批发", "批发商"], "zh_tw": ["批發", "批發商"],
        "ja": ["卸売", "問屋"], "ko": ["도매", "도매상"],
        "de": ["Großhandel", "Großhändler"], "nl": ["groothandel"],
        "fr": ["gros", "grossiste"], "es": ["mayorista", "al por mayor"],
        "pt": ["atacado", "atacadista"], "it": ["ingrosso", "grossista"],
        "ru": ["оптовая торговля", "оптовик"], "ar": ["تجارة الجملة", "تاجر جملة"],
        "th": ["ค้าส่ง", "ผู้ค้าส่ง"], "ms": ["borong", "pemborong"], "vi": ["bán buôn", "nhà bán sỉ"],
    },
    "brand": {
        "zh": ["品牌", "商标"], "zh_tw": ["品牌", "商標"],
        "ja": ["ブランド", "商標"], "ko": ["브랜드", "상표"],
        "de": ["Marke", "Markenzeichen"], "nl": ["merk", "handelsmerk"],
        "fr": ["marque"], "es": ["marca"],
        "pt": ["marca"], "it": ["marchio", "brand"],
        "ru": ["бренд", "торговая марка"], "ar": ["علامة تجارية", "ماركة"],
        "th": ["แบรนด์", "เครื่องหมายการค้า"], "ms": ["jenama"], "vi": ["thương hiệu", "nhãn hiệu"],
    },

    # MANUFACTURING
    "factory": {
        "zh": ["工厂", "制造商", "生产商"], "zh_tw": ["工廠", "製造商"],
        "ja": ["工場", "メーカー", "製造業者"], "ko": ["공장", "제조업체"],
        "de": ["Fabrik", "Hersteller", "Produktionsstätte"], "nl": ["fabriek", "producent"],
        "fr": ["usine", "fabricant", "producteur"], "es": ["fábrica", "fabricante", "productor"],
        "pt": ["fábrica", "fabricante"], "it": ["fabbrica", "produttore"],
        "ru": ["завод", "фабрика", "производитель"], "ar": ["مصنع", "شركة تصنيع"],
        "th": ["โรงงาน", "ผู้ผลิต"], "ms": ["kilang", "pengilang"], "vi": ["nhà máy", "nhà sản xuất"],
    },
    "oem": {
        "zh": ["代工", "OEM", "贴牌"], "zh_tw": ["代工", "OEM"],
        "ja": ["OEM", "受託製造"], "ko": ["OEM", "위탁 생산"],
        "de": ["Lohnfertigung", "OEM", "Auftragsfertigung"], "nl": ["loonproductie", "OEM"],
        "fr": ["fabrication à façon", "OEM"], "es": ["fabricación por contrato", "OEM"],
        "pt": ["fabricação terceirizada", "OEM"], "it": ["produzione conto terzi", "OEM"],
        "ru": ["производство по контракту", "ОЕМ"], "ar": ["التصنيع بموجب العقد", "OEM"],
        "th": ["รับจ้างผลิต", "OEM"], "ms": ["pengeluaran kontrak", "OEM"], "vi": ["gia công", "OEM"],
    },

    # MEDIA & ENTERTAINMENT
    "music": {
        "zh": ["音乐", "音乐人", "乐队"], "zh_tw": ["音樂", "音樂人"],
        "ja": ["音楽", "ミュージシャン", "バンド"], "ko": ["음악", "뮤지션", "밴드"],
        "de": ["Musik", "Musiker", "Band"], "nl": ["muziek", "muzikant"],
        "fr": ["musique", "musicien"], "es": ["música", "músico"],
        "pt": ["música", "músico"], "it": ["musica", "musicista"],
        "ru": ["музыка", "музыкант"], "ar": ["موسيقى", "موسيقي"],
        "th": ["ดนตรี", "นักดนตรี"], "ms": ["muzik", "pemuzik"], "vi": ["âm nhạc", "nhạc sĩ"],
    },
    "film": {
        "zh": ["电影", "影视", "视频制作"], "zh_tw": ["電影", "影視"],
        "ja": ["映画", "動画制作"], "ko": ["영화", "영상 제작"],
        "de": ["Film", "Kino", "Videoproduktion"], "nl": ["film", "bioscoop", "videoproductie"],
        "fr": ["film", "cinéma", "production vidéo"], "es": ["película", "cine", "producción audiovisual"],
        "pt": ["filme", "cinema", "produção audiovisual"], "it": ["film", "cinema", "produzione video"],
        "ru": ["кино", "фильм", "видеопроизводство"], "ar": ["فيلم", "سينما"],
        "th": ["ภาพยนตร์", "ผลิตวิดีโอ"], "ms": ["filem", "penerbitan video"], "vi": ["phim", "điện ảnh"],
    },
    "advertising": {
        "zh": ["广告", "营销", "品牌推广"], "zh_tw": ["廣告", "行銷"],
        "ja": ["広告", "マーケティング"], "ko": ["광고", "마케팅"],
        "de": ["Werbung", "Marketing", "Werbeagentur"], "nl": ["reclame", "marketing"],
        "fr": ["publicité", "communication", "agence"], "es": ["publicidad", "marketing"],
        "pt": ["publicidade", "marketing"], "it": ["pubblicità", "marketing"],
        "ru": ["реклама", "маркетинг"], "ar": ["إعلان", "تسويق"],
        "th": ["โฆษณา", "การตลาด"], "ms": ["iklan", "pemasaran"], "vi": ["quảng cáo", "marketing"],
    },
    "social_media": {
        "zh": ["社交媒体", "自媒体", "网红"], "zh_tw": ["社群媒體", "網紅"],
        "ja": ["SNS", "ソーシャルメディア", "インフルエンサー"], "ko": ["소셜미디어", "인플루언서"],
        "de": ["Social Media", "sozialen Medien"], "nl": ["sociale media"],
        "fr": ["réseaux sociaux", "médias sociaux"], "es": ["redes sociales", "medios sociales"],
        "pt": ["redes sociais", "mídia social"], "it": ["social media"],
        "ru": ["социальные сети", "соцсети"], "ar": ["وسائل التواصل الاجتماعي"],
        "th": ["โซเชียลมีเดีย"], "ms": ["media sosial"], "vi": ["mạng xã hội"],
    },

    # FASHION
    "clothing": {
        "zh": ["服装", "服饰", "时尚"], "zh_tw": ["服裝", "服飾", "時尚"],
        "ja": ["アパレル", "ファッション", "衣服"], "ko": ["패션", "의류", "의복"],
        "de": ["Bekleidung", "Mode", "Textil"], "nl": ["kleding", "mode"],
        "fr": ["habillement", "mode", "vêtement"], "es": ["ropa", "moda", "vestimenta"],
        "pt": ["roupa", "moda", "vestuário"], "it": ["abbigliamento", "moda"],
        "ru": ["одежда", "мода", "текстиль"], "ar": ["ملابس", "أزياء", "موضة"],
        "th": ["เสื้อผ้า", "แฟชั่น"], "ms": ["pakaian", "fesyen"], "vi": ["quần áo", "thời trang"],
    },
    "footwear": {
        "zh": ["鞋", "鞋类", "运动鞋"], "zh_tw": ["鞋子", "運動鞋"],
        "ja": ["靴", "フットウェア", "スニーカー"], "ko": ["신발", "운동화"],
        "de": ["Schuhe", "Schuhwerk", "Sneaker"], "nl": ["schoenen"],
        "fr": ["chaussures", "chaussure"], "es": ["calzado", "zapatos"],
        "pt": ["calçado", "sapatos"], "it": ["calzature", "scarpe"],
        "ru": ["обувь", "кроссовки"], "ar": ["أحذية"],
        "th": ["รองเท้า"], "ms": ["kasut"], "vi": ["giày dép"],
    },

    # AUTOMOTIVE
    "car": {
        "zh": ["汽车", "车辆"], "zh_tw": ["汽車", "車輛"],
        "ja": ["車", "自動車", "乗り物"], "ko": ["자동차", "차량"],
        "de": ["Auto", "Fahrzeug", "PKW"], "nl": ["auto", "voertuig"],
        "fr": ["voiture", "automobile", "véhicule"], "es": ["coche", "automóvil", "vehículo"],
        "pt": ["carro", "automóvel", "veículo"], "it": ["auto", "automobile", "veicolo"],
        "ru": ["автомобиль", "машина", "транспортное средство"], "ar": ["سيارة", "مركبة"],
        "th": ["รถยนต์", "รถ"], "ms": ["kereta", "kenderaan"], "vi": ["ô tô", "xe hơi"],
    },
    "transport": {
        "zh": ["运输", "物流", "交通"], "zh_tw": ["運輸", "物流", "交通"],
        "ja": ["輸送", "物流", "交通"], "ko": ["운송", "물류", "교통"],
        "de": ["Transport", "Logistik", "Verkehr"], "nl": ["transport", "logistiek"],
        "fr": ["transport", "logistique"], "es": ["transporte", "logística"],
        "pt": ["transporte", "logística"], "it": ["trasporto", "logistica"],
        "ru": ["транспорт", "логистика"], "ar": ["نقل", "لوجستيات"],
        "th": ["การขนส่ง", "โลจิสติกส์"], "ms": ["pengangkutan", "logistik"], "vi": ["vận tải", "logistics"],
    },

    # CONSTRUCTION
    "architect": {
        "zh": ["建筑师", "建筑设计"], "zh_tw": ["建築師", "建築設計"],
        "ja": ["建築家", "設計士"], "ko": ["건축가", "설계사"],
        "de": ["Architekt", "Architektur"], "nl": ["architect", "architectuur"],
        "fr": ["architecte", "architecture"], "es": ["arquitecto", "arquitectura"],
        "pt": ["arquiteto", "arquitetura"], "it": ["architetto", "architettura"],
        "ru": ["архитектор", "архитектура"], "ar": ["مهندس معماري", "عمارة"],
        "th": ["สถาปนิก", "สถาปัตยกรรม"], "ms": ["arkitek", "senibina"], "vi": ["kiến trúc sư", "kiến trúc"],
    },
    "contractor": {
        "zh": ["承包商", "建筑公司", "工程公司"], "zh_tw": ["承包商", "建設公司"],
        "ja": ["請負業者", "建設会社"], "ko": ["시공사", "건설업체"],
        "de": ["Auftragnehmer", "Bauunternehmen"], "nl": ["aannemer", "bouwbedrijf"],
        "fr": ["entrepreneur", "entreprise de construction"], "es": ["contratista", "empresa constructora"],
        "pt": ["empreiteiro", "construtora"], "it": ["appaltatore", "impresa edile"],
        "ru": ["подрядчик", "строительная компания"], "ar": ["مقاول", "شركة بناء"],
        "th": ["ผู้รับเหมา", "บริษัทก่อสร้าง"], "ms": ["kontraktor", "syarikat pembinaan"], "vi": ["nhà thầu", "công ty xây dựng"],
    },

    # EVENTS
    "conference": {
        "zh": ["会议", "峰会", "论坛"], "zh_tw": ["會議", "高峰會", "論壇"],
        "ja": ["会議", "カンファレンス", "サミット"], "ko": ["컨퍼런스", "회의", "정상회의"],
        "de": ["Konferenz", "Tagung", "Gipfel"], "nl": ["conferentie", "congres"],
        "fr": ["conférence", "sommet", "congrès"], "es": ["conferencia", "cumbre", "congreso"],
        "pt": ["conferência", "congresso", "cúpula"], "it": ["conferenza", "convegno", "summit"],
        "ru": ["конференция", "саммит", "съезд"], "ar": ["مؤتمر", "قمة"],
        "th": ["การประชุม", "การสัมมนา"], "ms": ["persidangan", "konvensyen"], "vi": ["hội nghị", "hội thảo"],
    },
    "event_planning": {
        "zh": ["活动策划", "赛事组织"], "zh_tw": ["活動策劃", "賽事組織"],
        "ja": ["イベント企画", "イベント運営"], "ko": ["이벤트 기획", "행사 기획"],
        "de": ["Eventplanung", "Veranstaltungsmanagement"], "nl": ["evenementenorganisatie"],
        "fr": ["organisation d'événements", "event management"], "es": ["organización de eventos"],
        "pt": ["organização de eventos", "gestão de eventos"], "it": ["organizzazione eventi"],
        "ru": ["организация мероприятий", "event-менеджмент"], "ar": ["تنظيم الفعاليات"],
        "th": ["จัดงาน", "ออร์แกไนเซอร์"], "ms": ["penganjuran acara"], "vi": ["tổ chức sự kiện"],
    },
    "exhibition": {
        "zh": ["展览", "展会", "博览会"], "zh_tw": ["展覽", "展會", "博覽會"],
        "ja": ["展示会", "見本市", "エキスポ"], "ko": ["전시회", "박람회"],
        "de": ["Ausstellung", "Messe", "Expo"], "nl": ["tentoonstelling", "beurs"],
        "fr": ["exposition", "salon", "foire"], "es": ["exposición", "feria", "salón"],
        "pt": ["exposição", "feira", "expo"], "it": ["esposizione", "fiera", "mostra"],
        "ru": ["выставка", "ярмарка", "экспо"], "ar": ["معرض", "بازار"],
        "th": ["งานแสดงสินค้า", "นิทรรศการ"], "ms": ["pameran", "ekspo"], "vi": ["triển lãm", "hội chợ"],
    },

    # HR & RECRUITMENT
    "recruitment": {
        "zh": ["招聘", "人才招募", "猎头"], "zh_tw": ["招聘", "人才招募", "獵頭"],
        "ja": ["採用", "リクルート", "人材紹介"], "ko": ["채용", "리크루팅", "헤드헌팅"],
        "de": ["Personalbeschaffung", "Recruitment", "Headhunting"], "nl": ["werving", "recruitment"],
        "fr": ["recrutement", "embauche", "chasse de têtes"], "es": ["reclutamiento", "contratación"],
        "pt": ["recrutamento", "seleção de pessoal"], "it": ["reclutamento", "selezione"],
        "ru": ["рекрутинг", "найм", "подбор персонала"], "ar": ["توظيف", "استقطاب"],
        "th": ["สรรหาบุคลากร", "รับสมัครงาน"], "ms": ["pengambilan pekerja", "recruitment"], "vi": ["tuyển dụng", "nhân sự"],
    },

    # ENERGY
    "renewable": {
        "zh": ["可再生能源", "太阳能", "风能", "绿色能源"], "zh_tw": ["再生能源", "太陽能"],
        "ja": ["再生可能エネルギー", "太陽光発電", "風力"], "ko": ["재생에너지", "태양광", "풍력"],
        "de": ["erneuerbare Energie", "Solar", "Wind", "Ökostrom"], "nl": ["hernieuwbare energie", "zonne-energie"],
        "fr": ["énergie renouvelable", "solaire", "éolien"], "es": ["energía renovable", "solar", "eólica"],
        "pt": ["energia renovável", "solar", "eólica"], "it": ["energia rinnovabile", "solare", "eolico"],
        "ru": ["возобновляемая энергия", "солнечная энергия", "ветроэнергетика"],
        "ar": ["طاقة متجددة", "طاقة شمسية", "طاقة الرياح"],
        "th": ["พลังงานหมุนเวียน", "พลังงานแสงอาทิตย์"], "ms": ["tenaga boleh diperbaharui", "solar"],
        "vi": ["năng lượng tái tạo", "điện mặt trời"],
    },

    # LOGISTICS
    "freight": {
        "zh": ["货运", "货物运输", "物流"], "zh_tw": ["貨運", "物流"],
        "ja": ["貨物", "フレート", "物流"], "ko": ["화물", "물류"],
        "de": ["Fracht", "Güterverkehr", "Spedition"], "nl": ["vracht", "expeditie"],
        "fr": ["fret", "transport de marchandises"], "es": ["flete", "mercancías", "carga"],
        "pt": ["frete", "carga", "transporte de mercadorias"], "it": ["trasporto merci", "spedizione"],
        "ru": ["грузоперевозки", "фрахт", "логистика"], "ar": ["شحن", "بضائع", "نقل"],
        "th": ["ขนส่งสินค้า", "โลจิสติกส์"], "ms": ["kargo", "pengangkutan barang"], "vi": ["vận chuyển hàng hóa", "logistics"],
    },
    "warehouse": {
        "zh": ["仓库", "仓储", "库房"], "zh_tw": ["倉庫", "倉儲"],
        "ja": ["倉庫", "貯蔵"], "ko": ["창고", "물류센터"],
        "de": ["Lager", "Lagerhaltung", "Lagerhaus"], "nl": ["magazijn", "opslag"],
        "fr": ["entrepôt", "stockage"], "es": ["almacén", "bodega", "almacenaje"],
        "pt": ["armazém", "depósito"], "it": ["magazzino", "deposito"],
        "ru": ["склад", "хранение"], "ar": ["مستودع", "مخزن"],
        "th": ["คลังสินค้า"], "ms": ["gudang", "stor"], "vi": ["kho hàng"],
    },

    # AGRICULTURE
    "farming": {
        "zh": ["农业", "农场", "种植"], "zh_tw": ["農業", "農場"],
        "ja": ["農業", "農場", "農作"], "ko": ["농업", "농장"],
        "de": ["Landwirtschaft", "Bauernhof"], "nl": ["landbouw", "boerderij"],
        "fr": ["agriculture", "ferme"], "es": ["agricultura", "granja"],
        "pt": ["agricultura", "fazenda"], "it": ["agricoltura", "azienda agricola"],
        "ru": ["сельское хозяйство", "ферма"], "ar": ["زراعة", "مزرعة"],
        "th": ["เกษตรกรรม", "ฟาร์ม"], "ms": ["pertanian", "ladang"], "vi": ["nông nghiệp", "nông trại"],
    },

    # BEAUTY
    "salon": {
        "zh": ["美发店", "沙龙", "理发店"], "zh_tw": ["美髮店", "沙龍"],
        "ja": ["サロン", "美容室", "理髪店"], "ko": ["미용실", "살롱"],
        "de": ["Salon", "Friseursalon", "Barbier"], "nl": ["salon", "kapsalon"],
        "fr": ["salon de coiffure", "salon de beauté"], "es": ["salón de belleza", "peluquería"],
        "pt": ["salão de beleza", "cabeleireiro"], "it": ["parrucchiere", "salone"],
        "ru": ["парикмахерская", "салон красоты"], "ar": ["صالون تجميل", "مصفف شعر"],
        "th": ["ร้านทำผม", "ร้านเสริมสวย"], "ms": ["salun kecantikan"], "vi": ["tiệm tóc", "salon làm đẹp"],
    },
    "skincare": {
        "zh": ["护肤", "化妆品", "美容"], "zh_tw": ["護膚", "化妝品"],
        "ja": ["スキンケア", "化粧品", "美容"], "ko": ["스킨케어", "화장품"],
        "de": ["Hautpflege", "Kosmetik", "Schönheitspflege"], "nl": ["huidverzorging", "cosmetica"],
        "fr": ["soins de la peau", "cosmétiques", "beauté"], "es": ["cuidado de la piel", "cosmética"],
        "pt": ["cuidados com a pele", "cosméticos"], "it": ["cura della pelle", "cosmetici"],
        "ru": ["уход за кожей", "косметика"], "ar": ["العناية بالبشرة", "مستحضرات التجميل"],
        "th": ["ดูแลผิว", "เครื่องสำอาง"], "ms": ["penjagaan kulit", "kosmetik"], "vi": ["chăm sóc da", "mỹ phẩm"],
    },

    # GENERAL
    "contact": {
        "zh": ["联系方式", "联系", "电话", "邮箱"], "zh_tw": ["聯絡方式", "聯繫"],
        "ja": ["お問い合わせ", "連絡先"], "ko": ["연락처", "문의"],
        "de": ["Kontakt", "Kontaktdaten", "Ansprechpartner"], "nl": ["contact", "contactgegevens"],
        "fr": ["contact", "coordonnées"], "es": ["contacto", "datos de contacto"],
        "pt": ["contato", "dados de contato"], "it": ["contatto", "recapiti"],
        "ru": ["контакт", "контактные данные"], "ar": ["جهة الاتصال", "معلومات الاتصال"],
        "th": ["ติดต่อ", "ข้อมูลติดต่อ"], "ms": ["hubungi", "maklumat hubungan"], "vi": ["liên hệ", "thông tin liên lạc"],
    },
    "international": {
        "zh": ["国际", "全球", "跨国"], "zh_tw": ["國際", "全球"],
        "ja": ["国際", "グローバル", "海外"], "ko": ["국제", "글로벌", "해외"],
        "de": ["international", "global", "weltweit"], "nl": ["internationaal", "globaal"],
        "fr": ["international", "mondial"], "es": ["internacional", "mundial"],
        "pt": ["internacional", "mundial"], "it": ["internazionale", "mondiale"],
        "ru": ["международный", "глобальный"], "ar": ["دولي", "عالمي"],
        "th": ["นานาชาติ", "ระดับโลก"], "ms": ["antarabangsa", "global"], "vi": ["quốc tế", "toàn cầu"],
    },
    "directory": {
        "zh": ["目录", "名录", "数据库"], "zh_tw": ["目錄", "名錄"],
        "ja": ["ディレクトリ", "名鑑", "リスト"], "ko": ["디렉토리", "목록"],
        "de": ["Verzeichnis", "Datenbank", "Katalog"], "nl": ["directory", "gids", "database"],
        "fr": ["annuaire", "répertoire", "catalogue"], "es": ["directorio", "guía", "catálogo"],
        "pt": ["diretório", "guia", "catálogo"], "it": ["directory", "elenco", "catalogo"],
        "ru": ["справочник", "каталог", "база данных"], "ar": ["دليل", "قائمة"],
        "th": ["ไดเรกทอรี", "คู่มือ"], "ms": ["direktori", "panduan"], "vi": ["thư mục", "danh bạ"],
    },
    "association": {
        "zh": ["协会", "联合会", "商会"], "zh_tw": ["協會", "聯合會"],
        "ja": ["協会", "連合会", "組合"], "ko": ["협회", "연합", "조합"],
        "de": ["Verband", "Vereinigung", "Handelskammer"], "nl": ["vereniging", "verbond"],
        "fr": ["association", "fédération", "chambre"], "es": ["asociación", "federación", "cámara"],
        "pt": ["associação", "federação", "câmara"], "it": ["associazione", "federazione"],
        "ru": ["ассоциация", "федерация", "палата"], "ar": ["جمعية", "اتحاد"],
        "th": ["สมาคม", "สหพันธ์"], "ms": ["persatuan", "persekutuan"], "vi": ["hiệp hội", "liên đoàn"],
    },
    "research": {
        "zh": ["研究", "研究机构", "调研"], "zh_tw": ["研究", "研究機構"],
        "ja": ["研究", "研究機関", "調査"], "ko": ["연구", "리서치"],
        "de": ["Forschung", "Studie", "Institut"], "nl": ["onderzoek", "studie"],
        "fr": ["recherche", "étude", "institut"], "es": ["investigación", "estudio", "instituto"],
        "pt": ["pesquisa", "estudo", "instituto"], "it": ["ricerca", "studio", "istituto"],
        "ru": ["исследование", "научное учреждение"], "ar": ["بحث", "دراسة"],
        "th": ["วิจัย", "การศึกษา"], "ms": ["penyelidikan", "kajian"], "vi": ["nghiên cứu", "viện"],
    },
    "network": {
        "zh": ["网络", "人脉", "社群"], "zh_tw": ["網路", "人脈"],
        "ja": ["ネットワーク", "人脈", "コミュニティ"], "ko": ["네트워크", "인맥", "커뮤니티"],
        "de": ["Netzwerk", "Gemeinschaft", "Forum"], "nl": ["netwerk", "gemeenschap"],
        "fr": ["réseau", "communauté"], "es": ["red", "comunidad"],
        "pt": ["rede", "comunidade"], "it": ["rete", "comunità"],
        "ru": ["сеть", "сообщество", "нетворкинг"], "ar": ["شبكة", "مجتمع"],
        "th": ["เครือข่าย", "ชุมชน"], "ms": ["rangkaian", "komuniti"], "vi": ["mạng lưới", "cộng đồng"],
    },

    # CRYPTO / BLOCKCHAIN
    "blockchain": {
        "zh": ["区块链", "加密货币", "比特币"], "zh_tw": ["區塊鏈", "加密貨幣"],
        "ja": ["ブロックチェーン", "仮想通貨", "暗号通貨"], "ko": ["블록체인", "암호화폐"],
        "de": ["Blockchain", "Kryptowährung"], "nl": ["blockchain", "cryptomunt"],
        "fr": ["blockchain", "cryptomonnaie"], "es": ["blockchain", "criptomoneda"],
        "pt": ["blockchain", "criptomoeda"], "it": ["blockchain", "criptovaluta"],
        "ru": ["блокчейн", "криптовалюта"], "ar": ["سلسلة الكتل", "عملة مشفرة"],
        "th": ["บล็อกเชน", "สกุลเงินดิจิทัล"], "ms": ["blockchain", "mata wang kripto"], "vi": ["blockchain", "tiền mã hóa"],
    },

    # GAMING
    "video_games": {
        "zh": ["游戏", "电子游戏", "视频游戏"], "zh_tw": ["遊戲", "電玩", "電子遊戲"],
        "ja": ["ゲーム", "テレビゲーム"], "ko": ["게임", "비디오 게임"],
        "de": ["Videospiel", "Spiel", "Gaming"], "nl": ["videospel", "gaming"],
        "fr": ["jeu vidéo", "gaming"], "es": ["videojuego", "gaming"],
        "pt": ["videogame", "jogo eletrônico"], "it": ["videogioco", "gaming"],
        "ru": ["видеоигра", "игра", "гейминг"], "ar": ["ألعاب الفيديو"],
        "th": ["เกม", "วิดีโอเกม"], "ms": ["permainan video", "gaming"], "vi": ["trò chơi điện tử", "game"],
    },
    "esports_gaming": {
        "zh": ["电子竞技", "电竞"], "zh_tw": ["電子競技", "電競"],
        "ja": ["eスポーツ", "電子競技"], "ko": ["e스포츠", "전자스포츠"],
        "de": ["Esports", "E-Sport", "professionelles Gaming"], "nl": ["esports"],
        "fr": ["esport", "jeux compétitifs"], "es": ["esports", "deportes electrónicos"],
        "pt": ["esports", "esporte eletrônico"], "it": ["esport", "gaming competitivo"],
        "ru": ["киберспорт", "соревновательный гейминг"], "ar": ["الرياضات الإلكترونية"],
        "th": ["อีสปอร์ต"], "ms": ["esport"], "vi": ["thể thao điện tử", "esports"],
    },
}
